# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2e5b77fe2512dc45c1e39ca2a88132b158e8e17f755a0bb15c85c57a11978284d2adb1abfadda2bba3ebe593e58bb69887cb94334f91acd75df9a06c4dc3b52e

test:
  secret_key_base: dddd1fee1f61eaab381125b12866a67527d474f0cfef87bbf4d3de0f72b777e9d23ebed2a744513bebbc8c8aaa07d7b7e78af7cf3ad9bf8937efab212263a340

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
